spring:
  application:
    name: payment-service
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/test
    username: root
    password: nhn123!@#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

psp:
  toss:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com

